# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import todo_pb2 as todo__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in todo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TodoStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTodo = channel.unary_unary(
                '/todoPackage.Todo/CreateTodo',
                request_serializer=todo__pb2.CreateTodoRequest.SerializeToString,
                response_deserializer=todo__pb2.TodoItem.FromString,
                _registered_method=True)
        self.GetTodo = channel.unary_unary(
                '/todoPackage.Todo/GetTodo',
                request_serializer=todo__pb2.GetTodoRequest.SerializeToString,
                response_deserializer=todo__pb2.TodoItem.FromString,
                _registered_method=True)
        self.ListTodos = channel.unary_unary(
                '/todoPackage.Todo/ListTodos',
                request_serializer=todo__pb2.Empty.SerializeToString,
                response_deserializer=todo__pb2.TodoItems.FromString,
                _registered_method=True)
        self.ListTodosStream = channel.unary_stream(
                '/todoPackage.Todo/ListTodosStream',
                request_serializer=todo__pb2.Empty.SerializeToString,
                response_deserializer=todo__pb2.TodoItem.FromString,
                _registered_method=True)
        self.UpdateTodo = channel.unary_unary(
                '/todoPackage.Todo/UpdateTodo',
                request_serializer=todo__pb2.UpdateTodoRequest.SerializeToString,
                response_deserializer=todo__pb2.TodoItem.FromString,
                _registered_method=True)
        self.DeleteTodo = channel.unary_unary(
                '/todoPackage.Todo/DeleteTodo',
                request_serializer=todo__pb2.DeleteTodoRequest.SerializeToString,
                response_deserializer=todo__pb2.Empty.FromString,
                _registered_method=True)


class TodoServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateTodo(self, request, context):
        """CREATE
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTodo(self, request, context):
        """READ
        Single item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTodos(self, request, context):
        """Multiple items - Unary - all at once
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTodosStream(self, request, context):
        """Streaming variant - Streaming - one at a time
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTodo(self, request, context):
        """UPDATE
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTodo(self, request, context):
        """DELETE
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TodoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTodo,
                    request_deserializer=todo__pb2.CreateTodoRequest.FromString,
                    response_serializer=todo__pb2.TodoItem.SerializeToString,
            ),
            'GetTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTodo,
                    request_deserializer=todo__pb2.GetTodoRequest.FromString,
                    response_serializer=todo__pb2.TodoItem.SerializeToString,
            ),
            'ListTodos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTodos,
                    request_deserializer=todo__pb2.Empty.FromString,
                    response_serializer=todo__pb2.TodoItems.SerializeToString,
            ),
            'ListTodosStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ListTodosStream,
                    request_deserializer=todo__pb2.Empty.FromString,
                    response_serializer=todo__pb2.TodoItem.SerializeToString,
            ),
            'UpdateTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTodo,
                    request_deserializer=todo__pb2.UpdateTodoRequest.FromString,
                    response_serializer=todo__pb2.TodoItem.SerializeToString,
            ),
            'DeleteTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTodo,
                    request_deserializer=todo__pb2.DeleteTodoRequest.FromString,
                    response_serializer=todo__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'todoPackage.Todo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('todoPackage.Todo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Todo:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todoPackage.Todo/CreateTodo',
            todo__pb2.CreateTodoRequest.SerializeToString,
            todo__pb2.TodoItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todoPackage.Todo/GetTodo',
            todo__pb2.GetTodoRequest.SerializeToString,
            todo__pb2.TodoItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTodos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todoPackage.Todo/ListTodos',
            todo__pb2.Empty.SerializeToString,
            todo__pb2.TodoItems.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTodosStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/todoPackage.Todo/ListTodosStream',
            todo__pb2.Empty.SerializeToString,
            todo__pb2.TodoItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todoPackage.Todo/UpdateTodo',
            todo__pb2.UpdateTodoRequest.SerializeToString,
            todo__pb2.TodoItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todoPackage.Todo/DeleteTodo',
            todo__pb2.DeleteTodoRequest.SerializeToString,
            todo__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
