# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x0btodoPackage\"\x06\n\x04void\"!\n\x11\x43reateTodoRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"$\n\x08TodoItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\"1\n\tTodoItems\x12$\n\x05items\x18\x01 \x03(\x0b\x32\x15.todoPackage.TodoItem2\x83\x01\n\x04Todo\x12\x43\n\ncreateTodo\x12\x1e.todoPackage.CreateTodoRequest\x1a\x15.todoPackage.TodoItem\x12\x36\n\treadTodos\x12\x11.todoPackage.void\x1a\x16.todoPackage.TodoItemsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOID']._serialized_start=27
  _globals['_VOID']._serialized_end=33
  _globals['_CREATETODOREQUEST']._serialized_start=35
  _globals['_CREATETODOREQUEST']._serialized_end=68
  _globals['_TODOITEM']._serialized_start=70
  _globals['_TODOITEM']._serialized_end=106
  _globals['_TODOITEMS']._serialized_start=108
  _globals['_TODOITEMS']._serialized_end=157
  _globals['_TODO']._serialized_start=160
  _globals['_TODO']._serialized_end=291
# @@protoc_insertion_point(module_scope)
